### ISSUE TITLE
3dfsb segfaults at f2109f440a1e1f584bc9336d0dc0b0e464cc7cc5

### ISSUE THREAD

**Issue by eduarrrd** [tomvanbraeckel/3dfsb#6]
Not sure why. Here's a backtrace:

```
Thread 1 (Thread 0x7f3efc766900 (LWP 25680)):
#0  pthread_cancel (th=0) at pthread_cancel.c:33
        pd = 0x0
        result = <optimized out>
        oldval = <optimized out>
        newval = <optimized out>
#1  0x0000000000409d54 in leodir () at 3dfsb.c:1863
        mode = 0
        temptype = 0
        texturewidth = 0
        textureheight = 0
        textureformat = 0
        textureid = 0
        linkpath = 0x88 <error: Cannot access memory at address 0x88>
        locpx = 0
        locpy = 0
        locpz = 0
        locsx = 1
        locsy = 1
        locsz = 1
        maxz = 0
        momx = 0
        momz = 0
        nextz = 0
        entry_list = 0x404700 <_start>
        entry = 0x40 <error: Cannot access memory at address 0x40>
        n = 64
        buf = {st_dev = 0, st_ino = 140733625729712, st_nlink = 0, st_mode = 6859768, st_uid = 0, st_gid = 0, __pad0 = 0, st_rdev = 140733625729712, st_size = 5, st_blksize = 112, st_blocks = 1, st_atim = {tv_sec = 139904264699953, tv_nsec = 0}, st_mtim = {tv_sec = 91, tv_nsec = 0}, st_ctim = {tv_sec = 0, tv_nsec = 511101108334}, __glibc_reserved = {0, 124, 139908498523185}}
        help = 0x69
        rowpos = 32574
        err = 32574
#2  0x000000000041184b in main (argc=1, argv=0x7fff19c502b8) at 3dfsb.c:3861
        fake_glut_argc = 1
        max_texture_size = 8192
```

 Let me know what else you need to help you fix this :-).

**Comment by tomvanbraeckel** [comment]
Thanks for the report! I think I've got this; we stop the thread, even if it had never been started or initialized yet. Strange that this never failed on me, but okay... Should be fixed just now, can you retry?

**Comment by eduarrrd** [comment]
Problem fixed, thanks!
