### ISSUE TITLE
3dsfb aborts at 3a479fa84a885cd2e77561564b4ac9bd4e63d89d

### ISSUE THREAD

**Issue by eduarrrd** [tomvanbraeckel/3dfsb#7]
Backtrace!

```
[New LWP 15490]
[New LWP 15288]
[New LWP 15287]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/nrxyygy0wqski1klq0305d3h523k41ps-glibc-2.20/lib/libthread_db.so.1".
Core was generated by `3dfsb'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f885c288157 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
Thread 3 (Thread 0x7f88604d3900 (LWP 15287)):
#0  _int_malloc (av=0x7f885c5eb640 <main_arena>, bytes=41533) at malloc.c:3433
        iters = 16
        nb = 41552
        idx = <optimized out>
        bin = <optimized out>
        victim = 0x26c0830
        size = <optimized out>
        victim_index = <optimized out>
        remainder = <optimized out>
        remainder_size = <optimized out>
        block = <optimized out>
        bit = <optimized out>
        map = <optimized out>
        fwd = <optimized out>
        bck = <optimized out>
        errstr = 0x0
        __func__ = "_int_malloc"
#1  0x00007f885c2ce4ce in __GI___libc_malloc (bytes=41533) at malloc.c:2890
        ar_ptr = 0x7f885c5eb640 <main_arena>
        victim = 0x7f885c5eb818 <main_arena+472>
        __func__ = "__libc_malloc"
#2  0x00007f88587665c6 in ReadInFile () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#3  0x00007f885876993c in XrmGetFileDatabase () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#4  0x00007f8858743ba9 in XGetErrorDatabaseText.part.0 () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#5  0x00007f8858743c5d in XGetErrorDatabaseText () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#6  0x00007f8858743dd8 in XGetErrorText () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#7  0x00007f8858762d38 in _XPrintDefaultError () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#8  0x00007f8858764463 in _XDefaultError () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#9  0x00007f885876458f in _XError () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#10 0x00007f88587616d7 in handle_error () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#11 0x00007f8858762777 in _XReply () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#12 0x00007f885ef0b263 in DRI2GetBuffersWithFormat () from /run/opengl-driver/lib/libGL.so.1
No symbol table info available.
#13 0x00007f885ef08b8b in dri2GetBuffersWithFormat () from /run/opengl-driver/lib/libGL.so.1
No symbol table info available.
#14 0x00007f884bf799aa in intel_update_renderbuffers () from /run/opengl-driver/lib/dri/i965_dri.so
No symbol table info available.
#15 0x00007f884bf79d63 in intel_prepare_render () from /run/opengl-driver/lib/dri/i965_dri.so
No symbol table info available.
#16 0x00007f884bf7dfd3 in brw_draw_prims () from /run/opengl-driver/lib/dri/i965_dri.so
No symbol table info available.
#17 0x00007f884be0f837 in vbo_exec_vtx_flush () from /run/opengl-driver/lib/dri/i965_dri.so
No symbol table info available.
#18 0x00007f884bdf7b6f in vbo_exec_FlushVertices_internal () from /run/opengl-driver/lib/dri/i965_dri.so
No symbol table info available.
#19 0x00007f884be0c916 in vbo_exec_FlushVertices () from /run/opengl-driver/lib/dri/i965_dri.so
No symbol table info available.
#20 0x00007f884bd829f9 in _mesa_Translatef () from /run/opengl-driver/lib/dri/i965_dri.so
No symbol table info available.
#21 0x000000000040ca9c in display () at 3dfsb.c:2589
        odist = 2.0812416517933342e-317
        vlen = 0
        senx = 0
        seny = 6.9279709072659432e-310
        senz = 0
        find_dist = 10000000
        find_entry = 0x0
        object = 0x2726970
        charpos = 72
        object_to_retexture = 0x0
        old_width = 4.57495923e-41
#22 0x000000000040b201 in standstillDisplay () at 3dfsb.c:2219
No locals.
#23 0x000000000041186b in main (argc=1, argv=0x7fff0a1c0b58) at 3dfsb.c:3867
        fake_glut_argc = 1
        max_texture_size = 8192

Thread 2 (Thread 0x7f885336f700 (LWP 15288)):
#0  0x00007f885f3bb8dd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x00007f885f61b779 in SDL_Delay () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#2  0x00007f885f61b7b2 in RunTimer () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#3  0x00007f885f5dc1d8 in SDL_RunThread () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#4  0x00007f885f619459 in RunThread () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#5  0x00007f885f3b4374 in start_thread (arg=0x7f885336f700) at pthread_create.c:310
        __res = <optimized out>
        pd = 0x7f885336f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140223488390912, -4725639989973946422, 0, 140223708307552, 0, 140223488390912, 4718506986222186442, 4718533268255993802}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007f885c337fbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 1 (Thread 0x7f88499f7700 (LWP 15490)):
#0  0x00007f885c288157 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 15287
        selftid = 15490
#1  0x00007f885c28955a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fff0a1c1843, sa_sigaction = 0x7fff0a1c1843}, sa_mask = {__val = {140223639662748, 140223576867819, 179, 4, 140223327458096, 48479818640, 1, 0, 0, 0, 0, 21474836480, 140223639662292, 140223327458248, 140223707025408, 140223639678136}}, sa_flags = 1484588051, sa_restorer = 0x7f88587d08b0 <__PRETTY_FUNCTION__.14033>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f885c281336 in __assert_fail_base (fmt=0x7f885c3b6cb8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f88587d0413 "!xcb_xlib_unknown_req_in_deq", file=file@entry=0x7f88587d03eb "xcb_io.c", line=line@entry=179, function=function@entry=0x7f88587d08b0 <__PRETTY_FUNCTION__.14033> "dequeue_pending_request") at assert.c:92
        str = 0x7f8844052d20 ""
        total = 4096
#3  0x00007f885c2813e2 in __GI___assert_fail (assertion=0x7f88587d0413 "!xcb_xlib_unknown_req_in_deq", file=0x7f88587d03eb "xcb_io.c", line=179, function=0x7f88587d08b0 <__PRETTY_FUNCTION__.14033> "dequeue_pending_request") at assert.c:101
No locals.
#4  0x00007f885876188c in dequeue_pending_request () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#5  0x00007f88587626b3 in _XReply () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#6  0x00007f885875e1ad in XSync () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#7  0x00007f8858740958 in XCloseDisplay () from /nix/store/r7cyay7ah01xsbznzzvjahbi52li211r-libX11-1.6.2/lib/libX11.so.6
No symbol table info available.
#8  0x00007f885f605951 in X11_VideoQuit () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#9  0x00007f885f5f901e in SDL_VideoQuit () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#10 0x00007f885f5d38c5 in SDL_QuitSubSystem () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#11 0x00007f885f5d396e in SDL_Quit () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#12 0x00007f885f5d3f4f in SDL_Parachute () from /nix/store/ajcm9vrpqaasgxdxrxm3gxi7l8l1233f-SDL-1.2.15/lib/libSDL-1.2.so.0
No symbol table info available.
#13 <signal handler called>
No locals.
#14 0x00007f8860060f8c in gst_mini_object_unref () from /nix/store/cjaqvqhpm6agkmyz78py8d2cl5lg4cly-gstreamer-1.4.3/lib/libgstreamer-1.0.so.0
No symbol table info available.
#15 0x0000000000404808 in gst_sample_unref (sample=0x7f886052a060 <_rtld_local>) at /nix/store/cjaqvqhpm6agkmyz78py8d2cl5lg4cly-gstreamer-1.4.3/include/gstreamer-1.0/gst/gstsample.h:96
No locals.
#16 0x0000000000405919 in get_image_from_file (filename=0x7f88499f5d30 "/home/e/Dropbox/Photos/BBC/_45636124_trio_afp_466.jpg", filetype=1) at 3dfsb.c:822
        sink = 0x0
        width = 0
        height = 0
        sample = 0x7f886052a060 <_rtld_local>
        descr = 0x7f8844052c00 "uridecodebin uri=file:///home/e/Dropbox/Photos/BBC/_45636124_trio_afp_466.jpg ! videoconvert ! videoscale ! appsink name=sink caps=\"video/x-raw,format=RGB\""
        error = 0x7f8844001650
        duration = 40586224
        position = 140223708307552
        ret = GST_STATE_CHANGE_FAILURE
        res = 0
        map = {memory = 0x0, flags = (GST_MAP_FLAG_LAST | unknown: 1235121920), data = 0x7f88499f6d50 "", size = 140223638549097, maxsize = 0, user_data = {0x3000000010, 0x7f88499f5cf0, 0x7f88499f5c30, 0x0}, _gst_reserved = {0x7f88499f5d30, 0x6a2e3636345f7066, 0x67706a, 0xffff}}
        uri = 0x7f8844052480 "file:///home/e/Dropbox/Photos/BBC/_45636124_trio_afp_466.jpg"
        max = 1
        buffer = 0x0
        loader = 0x7f884404fe90
        converter = 0x7f88440524d0
#17 0x0000000000405ae0 in async_load_textures (arg=0x0) at 3dfsb.c:860
        async_fullpath = "/home/e/Dropbox/Photos/BBC/_45636124_trio_afp_466.jpg", '\000' <repeats 4042 times>
        object = 0x26b4c80
#18 0x00007f885f3b4374 in start_thread (arg=0x7f88499f7700) at pthread_create.c:310
        __res = <optimized out>
        pd = 0x7f88499f7700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140223327467264, -4725639989973946422, 0, 140223708307552, 0, 140223327467264, 4718563263178665930, 4718533268255993802}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#19 0x00007f885c337fbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```

**Comment by tomvanbraeckel** [comment]
Thanks a lot for the report. I suspected that the /home/e/Dropbox/Photos/BBC/_45636124_trio_afp_466.jpg image was corrupt and could not be parsed by GStreamer. So I cleaned up our GStreamer error handling logic and when I enter a directory with broken images, it does not segfault or abort on the latest version. But when I tried this with an older build, it also didn't crash, so perhaps my test-image is not broken in the same way as yours. Anyway, can you please check if it is fixed and if not, mail that image on which is fails to me? Even if it is fixed, it would still be useful if you could send that image, so I can try to reproduce the abort that you had...

**Comment by eduarrrd** [comment]
Can't check right now but this is the image: http://newsimg.bbc.co.uk/media/images/45636000/jpg/_45636124_trio_afp_466.jpg

I'll let you know once have a chance to try out the new version.

**Comment by eduarrrd** [comment]
Problem no longer occurs.
